services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    image: dspfusion/app:latest
    ports: ["8000:8000"]
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ../frontend:/app/frontend:ro
  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    image: dspfusion/mlflow:latest
    ports: ["5000:5000"]
    volumes:
      - ../mlruns:/ml/mlruns
