FROM python:3.11-slim
RUN pip install --no-cache-dir mlflow
WORKDIR /ml
VOLUME ["/ml/mlruns"]
EXPOSE 5000
CMD ["mlflow","server","--host","0.0.0.0","--port","5000","--backend-store-uri","sqlite:///mlflow.db","--default-artifact-root","/ml/mlruns"]
